apiVersion: v1
kind: ConfigMap
metadata:
  name: fantaco-finance-config
  labels:
    app: fantaco-finance-main
data:
  database.url: "jdbc:postgresql://postgres-fin:5432/fantaco_finance"
  database.username: "postgres"
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    logging.level.com.customer=INFO
