apiVersion: v1
kind: Service
metadata:
  name: postgres-fin
  labels:
    app: postgres-fin
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres-fin
  selector:
    app: postgresql-finance